# Generated by Django 2.2 on 2022-12-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
