# Generated by Django 2.2 on 2023-03-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_changepassword_changepasswordcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='btc',
            field=models.CharField(blank=True, default='0.00', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='demon',
            field=models.CharField(default='10,000', max_length=50),
        ),
    ]
