# Generated by Django 2.2 on 2023-03-13 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_trade_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='opperation',
            new_name='operation',
        ),
    ]
