# Generated by Django 2.2 on 2023-03-14 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20230313_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('zipcode', models.CharField(default='0', max_length=50)),
                ('dob', models.CharField(default='0', max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('image1', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
