# Generated by Django 2.2 on 2023-03-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_kyc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profit',
            name='plan',
        ),
    ]
