# Generated by Django 2.2 on 2023-03-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_profit_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='totalbonus',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='totalrefbonus',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='totalwithdrawals',
        ),
    ]
