# Generated by Django 2.2 on 2024-02-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20230316_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='totaldeposit',
            new_name='active_inv',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='totalprofit',
            new_name='active_trade',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='accountbalance',
        ),
        migrations.AddField(
            model_name='customuser',
            name='copier',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.FileField(blank=True, default='https://res.cloudinary.com/danmybn7o/image/upload/v1649117194/media_cdn/pro_neycaw.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wal_bal',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
