# Generated by Django 2.2 on 2024-02-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20240219_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('link', models.CharField(default='', max_length=50)),
                ('category', models.CharField(choices=[('C', 'Crypto'), ('F', 'Futures'), ('C', 'Cfd'), ('S', 'Stocks'), ('FX', 'Forex')], max_length=10, null=True)),
            ],
        ),
    ]
