# Generated by Django 2.2 on 2024-02-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='asset',
            new_name='ex',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='operation',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='stock',
            new_name='profit',
        ),
        migrations.AddField(
            model_name='stock',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
