# Generated by Django 2.2 on 2024-02-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20240219_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='order',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
