# Generated by Django 2.2 on 2024-02-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20240219_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2001-03-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='msg',
            field=models.CharField(default='Running', max_length=50),
        ),
        migrations.AddField(
            model_name='trade',
            name='total',
            field=models.CharField(default='-----', max_length=50),
        ),
    ]
