# Generated by Django 2.2 on 2024-02-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20240220_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
