# Generated by Django 2.2 on 2024-02-24 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20240220_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copypro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('my_equity', models.CharField(max_length=200)),
                ('to_equity', models.CharField(max_length=200)),
                ('profit', models.CharField(blank=True, max_length=200)),
                ('loss', models.CharField(max_length=200)),
                ('track_id', models.CharField(default='0', max_length=10)),
                ('risk', models.CharField(default='0', max_length=20)),
                ('min', models.CharField(default='0', max_length=20)),
                ('copiers', models.CharField(default='0', max_length=20)),
                ('join', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='0', max_length=50)),
                ('duration', models.CharField(default='0', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Copypro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
