# Generated by Django 2.2 on 2024-02-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_copypro_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='copypro',
            name='image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
