# Generated by Django 2.2 on 2024-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_copypro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copypro',
            name='image',
            field=models.ImageField(default='pro.jpg', upload_to=''),
        ),
    ]
