# Generated by Django 2.2 on 2024-02-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20240224_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='pro',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
