# Generated by Django 2.2 on 2024-02-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20240224_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='slug',
        ),
        migrations.AddField(
            model_name='copypro',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
