# Generated by Django 2.2 on 2024-02-24 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20240224_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copypro',
            name='slug',
        ),
    ]
