# Generated by Django 2.2 on 2024-02-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_payment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
