# Generated by Django 2.2 on 2024-07-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20240227_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='copypro',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
